general:
  type: prod
  debug-log: false
  log-file-base-name: universal_prod
  allow-pwa: false
  pwa-version: 1
host:
  main-url: http://localhost:8080
scheduler:
  allow-sample-scheduler-job: false